[package]
name = "rust-chat"
version = "0.1.0"
authors = ["content-deleted <contentdeleted@gmail.com>"]

[[bin]]
name = "client"
path = "src/clientMain.rs"

[[bin]]
name = "server"
path = "src/serverMain.rs"

[dependencies]
azul = { git = "https://github.com/maps4print/azul" }
serde = "^1.0.62"